package com.opennxt.content.impl

import com.opennxt.Constants
import com.opennxt.model.lobby.DefaultVariables
import com.opennxt.model.world.WorldPlayer
import com.opennxt.net.game.serverprot.variables.VarpLarge
import com.opennxt.net.game.serverprot.variables.VarpSmall
import mu.KotlinLogging
import java.nio.file.Files

/**
 * The varps a reference client is given at login that this server never sends.
 */
object LoginVarps {

    private val logger = KotlinLogging.logger { }

    /**
     * `-Dopennxt.experiment.ui.loginVarps=true` enables it. **DEFAULT FLIPPED TO OFF**,
     * and this is a defect being switched off, not a preference.
     */
 // DEFAULT ON since evening: the two-account table (1,175 rows) was sent on run
    // server-20260905-170912 and a reference login came up as the reference client's default HUD - chatbox, one
    // action bar, backpack and skills docked, ribbon - and a layout save then held. That was the
    // "login with it ON has been looked at" this switch waited for. `=false` turns it off.
    val enabled: Boolean = System.getProperty("opennxt.experiment.ui.loginVarps") != "false"

    /**
     * How many varps a real reference login actually sets, decoded correctly.
     */
    const val WHAT_A_LOGIN_SETS = 3669

    private val path = Constants.DATA_PATH.resolve("config").resolve("login-varps.tsv")

    /** (varp, value, opcode) triples. Empty when the file is absent - see the class note. */
    val table: List<Triple<Int, Int, Int>> by lazy {
        if (!Files.exists(path)) return@lazy emptyList()
        val out = ArrayList<Triple<Int, Int, Int>>()
        var bad = 0
        Files.readAllLines(path).forEach { raw ->
            val line = raw.trim()
            if (line.isEmpty() || line.startsWith("#")) return@forEach
            val p = line.split('\t', ' ').filter { it.isNotBlank() }
            if (p.size < 2) { bad++; return@forEach }
            val id = p[0].toIntOrNull()
            val v = p[1].toLongOrNull()
            if (id == null || v == null) { bad++; return@forEach }
            // The generator records which opcode the reference client used. Falling back on the value's
            // own range rather than defaulting to one of them: a byte varp sent as an int
            // is a different packet from the one the client was built to expect.
            val op = p.getOrNull(2)?.toIntOrNull() ?: if (v > 127 || v < -128) 78 else 95
            out.add(Triple(id, v.toInt(), op))
        }
        if (bad > 0) logger.warn("login-varps.tsv: $bad unparseable line(s) skipped")
        out
    }

    /**
     * Send the table. Returns how many went out, so the caller's log line can carry a
     * number rather than an assurance.
     */
    fun send(player: WorldPlayer): Int {
        if (!enabled) {
            logger.info("ui.loginVarps=false: the reference login varp table is NOT being sent")
            return 0
        }
        val t = table
        if (t.isEmpty()) {
            logger.info(
                "ui.loginVarps: no table at $path, so nothing is sent. It is generated by " +
                    "comparing two recorded logins, and is gitignored " +
                    "like data/config/mods.json - see data/config/login-varps.example.tsv. " +
                    "This is not an error; a clone simply has no reference data."
            )
            return 0
        }
        var large = 0
        var small = 0
        var skipped = 0
        t.forEach { (id, v, op) ->
 // THE VARP GUARD.. Same predicate sendDefaultVarps uses.
            //
            // WHY, measured rather than assumed. This table had never actually been
            // sent: the deployed tree had no login-varps.tsv, so every previous run
            // logged "no table ... nothing is sent" and the experiment was inert. On
            // the first run where the file was present (
            // logs/server-20260903-225058) the client died 6.9s into the world with
            // fault offset 0x2e959d ->, which is the documented
            // VARP_SMALL undefined-id site: VAR_LOOKUP misses, returns
            // the zero-filled sentinel, and the store helper
            // reads [sentinel+8] -> [0+8] with no null check.
            //
            // 260 of this table's 323 ids are not among the cache's 13,267
            // varplayer definitions, which run 0..13539. 240 of those 260 sit in the
            // contiguous 0xFF00-0xFFFF block carrying values 2..52 - that is a
            // decoder artefact in tools/949/login_diff.py, not the reference client state, and it
            // means only 63 of the 323 rows are varps at all.
            //
            // This does NOT fix login_diff.py. It stops a CANDIDATE table derived
            // from an observation being trusted to name ids that exist - which was never
            // a safe assumption and is now a measured false one.
            if (!DefaultVariables.varpIsDefined(id)) { skipped++; return@forEach }
            if (op == 95 && v in -128..127) { player.client.write(VarpSmall(id, v)); small++ }
            else { player.client.write(VarpLarge(id, v)); large++ }
        }
        if (skipped > 0) {
            logger.warn(
                "ui.loginVarps: SKIPPED $skipped of ${t.size} rows whose varp id this cache does " +
                    "not define - sending any one of them crashes the client." +
                    "A large number here means login-varps.tsv is contaminated, not that the " +
                    "cache is short: regenerate it and see LoginVarps' varp-guard comment."
            )
        }
        logger.info(
            "ui.loginVarps: sent ${small + large} of ${t.size} varps a reference client gets at login and this server " +
                "never did ($large large, $small small). CANDIDATE defaults, invariant across two " +
                "reference logins - the weakest form of that evidence, see LoginVarps' KDoc. " +
                "-Dopennxt.experiment.ui.loginVarps=false removes them."
        )
        return t.size
    }
}
