package com.opennxt.content.impl

import com.opennxt.resources.sqlite.RsDatabase
import mu.KotlinLogging

/**
 * The chathead model ids an npc declares, straight out of the cache.
 */
object NpcHeadModels {

    private val logger = KotlinLogging.logger { }

    /** Cache of npc id -> first head model, or null when the npc declares none. */
    private val cache = HashMap<Int, Int?>()

    /** How many parts each npc's head has. Observable so a check can assert on it. */
    private val partCounts = HashMap<Int, Int>()

    /**
     * The FIRST chathead model id for [npcId], or null when the npc declares
     * none (or there is no definition database at all).
     */
    @Synchronized
    fun firstHeadModel(npcId: Int): Int? = cache.getOrPut(npcId) {
        if (!RsDatabase.hasTable("npcs_attr")) return@getOrPut null
        val raw = RsDatabase.queryOne(
            "SELECT value FROM npcs_attr WHERE id = ? AND field = 'headModels'", npcId
        ) { it.getString("value") } ?: return@getOrPut null
        val ids = parse(raw)
        partCounts[npcId] = ids.size
        ids.firstOrNull()
    }

    /** How many head parts [npcId] declares. 0 when it declares none. */
    @Synchronized
    fun partCount(npcId: Int): Int {
        firstHeadModel(npcId)
        return partCounts[npcId] ?: 0
    }

    /**
     * `[49449]` or `[39836,39223]` -> the ints.
     *
     * Deliberately tolerant: this is a decoded artefact regenerated by
     * `buildall.sh`, and one malformed row must not make an npc untalkable.
     * Anything that is not a run of digits is skipped.
     */
    fun parse(raw: String): List<Int> =
        Regex("-?\\d+").findAll(raw).mapNotNull { it.value.toIntOrNull() }.toList()

    /** Test seam. */
    @Synchronized
    internal fun clear() {
        cache.clear(); partCounts.clear()
    }
}
